version: "3.9"
services:
  api: &api
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ems
    command: python manage.py runserver 0.0.0.0:10007
    volumes:
      - ./:/app
    ports:
      - "10007:10007"
    env_file:
      - ./.env
    restart: always
    
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./.env

  celery:
    <<: *api
    command: celery -A core.celery worker --pool=threads --loglevel=info --logfile=logs/celery.log
    ports: []
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - celery

  dashboard:
    <<: *api
    command: celery --broker=${REDIS_URL} flower --port=5555
    ports:
      - "25559:5555"
    env_file:
      - ./.env
    depends_on:
      - api
      - celery

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/app
    command: -f /app/locustfile.py --master -H http://local-master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./:/app
    command: -f /app/locustfile.py --worker --master-host locust-master
