# Generated by Django 3.2.5 on 2021-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.IntegerField(unique=True),
        ),
    ]
