# Generated by Django 3.2.5 on 2021-08-01 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210801_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
