# Generated by Django 3.2.5 on 2021-08-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20210801_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
