# Generated by Django 3.2.5 on 2021-08-02 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='kids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
